version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysqldb
    ports:
      - 3307:3306
    environment:
       - MYSQL_DATABASE=ecore
       - MYSQL_ROOT_PASSWORD=root
    volumes:
        - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql